integration:
  s3-uploader:
    base-url: http://localhost:8082
    service: experian
    subservice: credit
  server:
     servlet:
     context-path: /mosaics3uploaderlibrary
    error:
      include-stacktrace: never
  #spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/culoansportal
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      idle-timeout: 30000
  #      maxPoolSize: 16
  # jpa:
  #   hibernate:
  #     ddl-auto: none
  #   database: MYSQL
  #   show-sql: true
#   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  #management:
  # endpoints:
  #   jmx:
  #    exposure:
  #      include:
  #        - health
  #        - info
  #  web:
  #    exposure:
  #      include:
  #       - health
#      - info

  #hibernate:
  #show_sql: true
  #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#storage_engine: innodb