apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployments.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pdbs.mosaics3uploaderlibrary.labels" . | indent 4 }}
type: Opaque
data:
  {{ range .Values.deployments.secrets.data }}
  {{ .name }} : "{{ .value }}"
  {{ end }}
  {{ if .Values.isDBUsed }}
  spring.datasource.username : "{{ .Values.databaseUserName }}"
  spring.datasource.password : "{{ .Values.databasePassword }}"
  {{ end }}
