apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pdbs.mosaics3uploaderlibrary.labels" . | indent 4 }}
  {{- with .Values.services.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.type }}
  ports:
    - port: {{ .Values.services.port }}
      targetPort: {{ .Values.deployments.containerPort }}
      protocol: {{ .Values.services.protocol }}
  selector:
    app: {{ .Values.deployments.labels.selectorApp }}
